### ISSUE TITLE
TY For Considering

### ISSUE THREAD

**Issue by meandrop123** [AventusSystems/aventus-dapp-proposals#21]

**Comment by annikamonari** [comment]
This proposal has been approved.

**Comment by walter-grace** [comment]
This is exactly what OpenBazzar does this with bitcoin, also with social media marketing Facebook now has selling on their platform.

**Comment by meandrop123** [comment]
Sella shares some parallels to these mentioned be true. In contrast to an optional bitcoin payment system, Sella aims to not use the AVT token (as possibly other ERC20 tokens using the Aventus Protocol) to provide a flexible system to pay for these services, but also to require payment through the AVT Services layer which ultimately provides the platforms major advantage over such services in the form of payment protection (by way of blockchain technology).  

The buyer protection/fraud protection offered by Sella can be seen in the form of the main components (the 'Sale' entities) acting as an intermediary to promote and facilitate a successful & trouble-free transaction.   

This 'middle man' type of behavior is very helpful in creating a smooth sequence of events for each sale.  This eliminates the need to carry around large sums of cash in physical sales, as well as the prevalence of chargeback/payment fraud which can be a plague on online digital asset sales.  

Secondly, the tiered verification system promotes further fair-play as fully verified persons can be permanently associated with negative experiences, (and likewise positive experiences), as their overall rating within Sella is tied to their unique personnel record (by SSN, Passport, etc). 

Offering incentives for successful trades, fair-play, and ratings participation is another feature that differentiates Sella from these services.  By using the Aventus incentives system, users are able to earn AVT by participating in the system, and by engaging in successful transactions.

Lastly, history and media assets will be accessible after sales.  Media assets and historical data will be available through IPFS which means you dont lose images or listings if you want to relist something from previous sales, and you also can pull up detailed records of transactions years into the future.

**Comment by annikamonari** [comment]
This proposal has been approved.
