### ISSUE TITLE
Doing Dutch 

### ISSUE THREAD

**Issue by Mez008** [AventusSystems/aventus-dapp-proposals#30]
## **Introduction**
 
The streamlined way to split bills. Ever paid for two concert tickets for you and a mate, then had to wait ages to be paid back? Or maybe you’re sick of your younger brother (or sister) always short changing you at the bar? Well fear no more, Doing Dutch is here, the easiest way to streamline your bills.
Doing Dutch will revolutionise your social life, no more awkward “hey, can you pay me back” texts, now, at a click of a button, a bill can be split and paid with ease
 
## Problem
 
The ticketing ecosystem ‘distributed commerce’ has been in place for many years. You could buy tickets at record stores, or at venues and physical locations. Now, we’re seeing a new model of distributed commerce emerge online. This is similar to the physical “expansion” we saw in the late 80s: people are now able to buy tickets wherever they go online. So instead of distributing ticket-buying across physical locations, we’re distributing ticket-buying across digital locations.

One of the worlds leading online ticketing platforms, Live Nation Entertainment. In 2010, Live Nation merged with Ticketmaster - the super company sold over 68 million tickets this year and revenue up 2.8 billion in the second quarter. Despite the elevating business, Live Nation has offered very little online innovation in ticketing over the past few years. 
 
E.G. An average ticket to see an artist like Beyoncè is around £80. Of course, you’re not going to see Beyoncè so if you’re buying for a group of your friends, one person will need to buy multiple tickets so everyone can sit and enjoy together.
 
1xBeyonce = £80
1x Fees = £5
Total 4x = £340
 
At the moment it’s not possible to simply split the purchase transaction during check out. That would be a hefty amount for one person to pay. This is one of the main issues surrounding the flexibility of payment methods the current ticketing services. It’s also a bit of an inconvenience to sit down and calculate exactly what your mates owes you. This is where Doing Dutch platform comes in and simplifies the process for users and event-goers.
 
 
##  Solution
 
Doing Dutch will be based on the block chain, this makes it different from conventional re-payment systems. Each purchase or spilt is stored as a smart contract with their own ID number. This will allow transparency for all parties.
 
Eg. Peter wants to book 3x tickets which totals £175. He splits the total bill with himself and his friends, Tobias and Eric. Both of them will receive a request to split.
 
When a split is requested a code will be added to the smart contract. The code will hold the split conditions, which is linked to the smart contract and automatically update once Eric and Tobias has accepted the payment.
Once the all participants have paid one smart contract will be updated and participants notified. With the contract ID number all updates can be monitored regarding the ticketing.
 
If a participant wish to sell their ticket the smart contract will be updated. By using the ID number the unique code which is linked to that part of the contract will be deleted on that ticket after it’s sold and the entire smart contract will be updated accordingly.
 
Peter, Tobias, and Eric will all hold their part of their ticket on the Doing Dutch app. This individual holding makes the practicalities of attending an event easier, users of Doing Dutch do not need to arrive as a group, they have full autonomy over their ticket.
 
Splitting cost before and during event can be done two ways:

1. Purchase a ticket with Doing Dutch, select the items, then select spilt and the person you wish to split with. They will receive a split request for the amount selected.
 
2. Purchase a product without Doing Dutch and request to split an amount with a person. Whilst creating a new repayment request a smart contract will be created according to the requesters submitted information.
 
![doing dutch](https://user-images.githubusercontent.com/31599833/30007314-3a8985c6-910c-11e7-9586-57c1dc63ddd3.png)

## Aventus Protocol and Overall Ecosystem

Doing Dutch will be a part of the Aventus application layer, which can be adopted by third party developers. Event organisers and promoters will receive their commission on a ticket sale or any other related products, according to the standard Aventus term and conditions in AVT.
 
To be able to purchase tickets via Doing Dutch you can only complete the payment with AVT tokens, this is also for third party. However, you can choose to split all other purchases with various currencies. By allowing the AVT token to be the main conversion currency it will enable growth increasing the adoption of the AVT token and Aventus community.

## Monetisation

Doing Dutch will focus on the primary market and on distributing the cost of the ticketing sales and any other sales linked to the event. The app could be sponsored through companies such as Stub Hub, Ticketmaster and other various ticketed events. In many cases events are the purpose for splitting costs therefore they double use the app to promote upcoming concerts and other events. This would provide an aspect of monetisation. Users could participate in a short survey when they download the app based on the kind of scenarios they would use the app for and thus the ads would be according to that. All users will incur a micro fee translation fee per split and deposit from debts or credit cards. 

Doing Dutch offers the user flexibility when needed less hassle and no more keeping tabs it’s all done in one simple click.

My Etherum adress: 0xc583498a651B3b47794448364551E8A196B1fdF7

**Comment by annikamonari** [comment]
This proposal has been approved.

**Comment by annikamonari** [comment]
@Mez008 Please edit the top post to have your Ethereum address so we can give you your participation reward.

**Comment by Mez008** [comment]
My Etherum address is 0xc583498a651B3b47794448364551E8A196B1fdF7

**Comment by Mez008** [comment]
Hey Annika,

I participated for the Dapp proposal contest, however, I haven't received
reward tokens.
https://github.com/AventusSystems/aventus-dapp-proposals/issues/30#issuecomment-332533938


My ether wallet is 0xc583498a651B3b47794448364551E8A196B1fdF7

Could you help me sort this out.

Many thanks.

2017-09-27 10:11 GMT-04:00 Annika Monari <notifications@github.com>:
